from dataclasses import dataclass

@dataclass
class Alert:
    """Represents a security alert generated by a detector."""

    alert_type: str
    severity: str
    description: str
    source_ip: str
    event_count: int
    first_seen: str
    last_seen: str